# Generated by Django 4.0.4 on 2022-05-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply_Record',
        ),
        migrations.AddField(
            model_name='hole_construction',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hole_construction',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='hole_design',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wash_coal_construction',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wash_coal_construction',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
