# Generated by Django 4.0.4 on 2022-06-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0004_wash_coal_construction_actual_flush_mei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wash_coal_construction',
            name='flush_water_pressure',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wash_coal_construction',
            name='kong_radius',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
