# Generated by Django 4.0.4 on 2022-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0005_wash_coal_construction_flush_water_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole_design',
            name='isNext',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
