# Generated by Django 4.0.4 on 2022-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0006_hole_design_isnext'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole_construction',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wash_coal_construction',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zhu_jiang_construction',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
