# Generated by Django 4.0.4 on 2022-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0007_hole_construction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole_design',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
