# Generated by Django 4.0.4 on 2022-07-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0008_hole_design_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='vedioCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_c_number', models.CharField(max_length=30)),
                ('isKaiKongShenQing', models.CharField(default='0', max_length=2)),
                ('isKaiKongJuPai', models.CharField(default='0', max_length=2)),
                ('isJianMeiJuPai', models.CharField(default='0', max_length=2)),
                ('isJianDingJuPai', models.CharField(default='0', max_length=2)),
                ('isZhongKongJuPai', models.CharField(default='0', max_length=2)),
                ('isTuiZuanYanShouJuPai', models.CharField(default='0', max_length=2)),
                ('isChongMeiYanShouJuPai', models.CharField(default='0', max_length=2)),
                ('isFengKongKaiShiJuPai', models.CharField(default='0', max_length=2)),
                ('isFengKongYanShouJuPai', models.CharField(default='0', max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mining.row')),
            ],
        ),
        migrations.CreateModel(
            name='ShiGongCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_c_number', models.CharField(max_length=30)),
                ('isQiQuan', models.CharField(default='0', max_length=2)),
                ('isCeXie', models.CharField(default='0', max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mining.row')),
            ],
        ),
    ]
